import {useEffect,useState} from 'react';
import {ActivityIndicator,Alert,FlatList,Image,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import * as ImagePicker from 'expo-image-picker';
import type {Session} from '@supabase/supabase-js';
import {supabase} from './lib/supabase';

type Profile={id:string;name?:string;username?:string;bio?:string;city?:string;job_title?:string;education?:string;interests?:string[];photos?:string[];dating_intention?:string};
const C={ink:'#183b3a',paper:'#fffaf5',coral:'#e96f51',soft:'#7c918d',line:'#e8ddd2'};
const Btn=({title,onPress,ghost=false}:{title:string;onPress:()=>void;ghost?:boolean})=><Pressable onPress={onPress} style={[s.btn,ghost&&s.ghost]}><Text style={[s.btnText,ghost&&{color:C.ink}]}>{title}</Text></Pressable>;

export default function App(){
 const [session,setSession]=useState<Session|null>(null),[busy,setBusy]=useState(true),[profile,setProfile]=useState<Profile|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setBusy(false)});const {data}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle().then(({data})=>setProfile(data));else setProfile(null)},[session]);
 if(busy)return <View style={s.center}><ActivityIndicator color={C.coral}/></View>;
 return <><StatusBar style="dark"/>{session?<Home profile={profile} reload={async()=>{const {data}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();setProfile(data)}}/>:<Auth/>}</>;
}

function Auth(){const [method,setMethod]=useState<'email'|'username'>('email'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[login,setLogin]=useState(true),[error,setError]=useState('');
 async function submit(){setError('');let address=email.trim();if(login&&method==='username'){const r=await supabase.rpc('resolve_login_username',{login_username:address});if(r.error||!r.data)return setError('Username or password is incorrect.');address=r.data}const r=login?await supabase.auth.signInWithPassword({email:address,password}):await supabase.auth.signUp({email:address,password});if(r.error)setError(r.error.message);else if(!r.data.session)Alert.alert('Check your email','Confirm your account, then log in.');}
 async function reset(){if(!email.includes('@'))return setError('Enter your email first.');const {error}=await supabase.auth.resetPasswordForEmail(email);setError(error?.message||'Password reset link sent.');}
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.auth}><Text style={s.logo}>stunner.</Text><Text style={s.h1}>{login?'Welcome back':'Create your account'}</Text>{login&&<View style={s.switch}><Pressable onPress={()=>setMethod('email')}><Text style={method==='email'?s.active:s.muted}>Email</Text></Pressable><Pressable onPress={()=>setMethod('username')}><Text style={method==='username'?s.active:s.muted}>Username</Text></Pressable></View>}<TextInput style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none" placeholder={method==='username'?'your_username':'you@example.com'}/><TextInput style={s.input} value={password} onChangeText={setPassword} secureTextEntry placeholder="Password (8+ characters)"/>{!!error&&<Text style={s.error}>{error}</Text>}<Btn title={login?'Log in':'Sign up'} onPress={submit}/>{login&&<Pressable onPress={reset}><Text style={s.link}>Forgot password?</Text></Pressable>}<Pressable onPress={()=>{setLogin(!login);setMethod('email');setError('')}}><Text style={s.link}>{login?'New here? Create an account':'Already have an account? Log in'}</Text></Pressable></KeyboardAvoidingView></SafeAreaView>}

function Home({profile,reload}:{profile:Profile|null;reload:()=>Promise<void>}){const [tab,setTab]=useState('Discover');return <SafeAreaView style={s.safe}><View style={s.top}><Text style={s.logo}>stunner.</Text></View><View style={{flex:1}}>{tab==='Discover'?<Discover/>:tab==='Matches'?<Matches/>:<ProfileView profile={profile} reload={reload}/>}</View><View style={s.tabs}>{['Discover','Matches','You'].map(x=><Pressable key={x} onPress={()=>setTab(x)}><Text style={tab===x?s.active:s.muted}>{x}</Text></Pressable>)}</View></SafeAreaView>}
function Discover(){const [cards,setCards]=useState<Profile[]>([]);useEffect(()=>{supabase.rpc('get_feed',{limit_n:30}).then(({data})=>setCards(data||[]))},[]);const p=cards[0];async function swipe(liked:boolean){if(!p)return;await supabase.from('swipes').insert({target:p.id,liked});setCards(v=>v.slice(1))}if(!p)return <View style={s.center}><Text style={s.h2}>You’re all caught up</Text><Text style={s.muted}>Check back for new verified people.</Text></View>;return <View style={s.page}>{p.photos?.[0]&&<Image source={{uri:p.photos[0]}} style={s.hero}/>}<Text style={s.h1}>{p.name}</Text><Text style={s.muted}>{[p.job_title,p.city].filter(Boolean).join(' · ')}</Text><Text style={s.bio}>{p.bio}</Text><View style={s.actions}><Btn title="Pass" ghost onPress={()=>swipe(false)}/><Btn title="Like ♥" onPress={()=>swipe(true)}/></View></View>}
function Matches(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{supabase.from('matches').select('*').order('created_at',{ascending:false}).then(({data})=>setItems(data||[]))},[]);return <View style={s.page}><Text style={s.h1}>Matches</Text><FlatList data={items} keyExtractor={x=>x.id} ListEmptyComponent={<Text style={s.muted}>New matches will appear here.</Text>} renderItem={({item})=><View style={s.row}><Text style={s.h2}>It’s a match ♥</Text><Text style={s.muted}>{new Date(item.created_at).toLocaleDateString()}</Text></View>}/></View>}
function ProfileView({profile,reload}:{profile:Profile|null;reload:()=>Promise<void>}){const [editing,setEditing]=useState(false),[bio,setBio]=useState(profile?.bio||''),[interests,setInterests]=useState((profile?.interests||[]).join(', '));async function save(){const {error}=await supabase.from('profiles').update({bio,interests:interests.split(',').map(x=>x.trim()).filter(Boolean).slice(0,5)}).eq('id',profile?.id);if(error)Alert.alert('Could not save',error.message);else{await reload();setEditing(false)}}async function addPhoto(){const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:6});if(!r.canceled)Alert.alert('Photos selected','Cloud upload wiring is the next build step.')}return <ScrollView contentContainerStyle={s.page}><Text style={s.h1}>{profile?.name||'Your profile'}</Text><Text style={s.muted}>@{profile?.username||'choose_username'}</Text>{editing?<><TextInput style={[s.input,{height:110}]} multiline value={bio} onChangeText={setBio} placeholder="About you"/><TextInput style={s.input} value={interests} onChangeText={setInterests} placeholder="Interests, separated by commas"/><Btn title="Choose photos (up to 6)" ghost onPress={addPhoto}/><Btn title="Save changes" onPress={save}/></>:<><Text style={s.bio}>{profile?.bio||'Add a bio so matches know you.'}</Text><View style={s.chips}>{profile?.interests?.map(x=><Text key={x} style={s.chip}>{x}</Text>)}</View><Btn title="Edit profile" onPress={()=>setEditing(true)}/><Btn title="Log out" ghost onPress={()=>supabase.auth.signOut()}/></>}</ScrollView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},auth:{flex:1,justifyContent:'center',padding:24,gap:14},logo:{fontSize:28,fontWeight:'900',color:C.ink},h1:{fontSize:30,fontWeight:'800',color:C.ink},h2:{fontSize:18,fontWeight:'700',color:C.ink},input:{backgroundColor:'#fff',borderWidth:1,borderColor:C.line,borderRadius:14,padding:15,fontSize:16},btn:{backgroundColor:C.coral,padding:15,borderRadius:16,alignItems:'center',flex:1},ghost:{backgroundColor:'#fff',borderWidth:1,borderColor:C.line},btnText:{color:'#fff',fontWeight:'800',fontSize:16},link:{textAlign:'center',color:C.ink,textDecorationLine:'underline',padding:5},error:{color:'#b33'},switch:{flexDirection:'row',gap:24},active:{color:C.coral,fontWeight:'800'},muted:{color:C.soft},top:{padding:18,borderBottomWidth:1,borderColor:C.line},tabs:{flexDirection:'row',justifyContent:'space-around',padding:18,borderTopWidth:1,borderColor:C.line,backgroundColor:'#fff'},page:{padding:18,gap:14},hero:{width:'100%',height:420,borderRadius:24,backgroundColor:C.line},bio:{fontSize:16,lineHeight:24,color:C.ink},actions:{flexDirection:'row',gap:12},row:{backgroundColor:'#fff',padding:16,borderRadius:16,marginVertical:6},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{backgroundColor:'#e9f1ef',color:C.ink,paddingHorizontal:12,paddingVertical:7,borderRadius:20}});
